SERVICE := "frontend"
SERVICE_TYPE := "nextjs"
VERSION := "local"

APP := SERVICE + "-" + SERVICE_TYPE
DOCKER_TAG := APP + ":" + VERSION
PORT := "-p 3000:3000"
TTY := `if tty -s; then echo "-it"; fi`

# Localized `just` command for this file only
just_local := "just --justfile " + source_file()

# Show these help docs
[default]
@help:
    echo "{{GREEN}}[MLAD] Next.js frontend{{NORMAL}}"
    echo "{{GREEN}}>> $(pwd){{NORMAL}}"
    echo ""
    just --list --unsorted --justfile {{ source_file() }}

# Remove lockfile and node_modules, then reinstall from scratch
[confirm("This will delete 'pnpm-lock.yaml' and 'node_modules/'.\nProceed? [y/N]")]
lock:
    rm -f pnpm-lock.yaml
    rm -rf node_modules
    {{just_local}} sync

# sync dependencies for this frontend
sync:
    pnpm install

# Run tests
test:
    pnpm run test

# Run tests, and watch for file changes to rerun
test-watch:
    pnpm run test:watch

# Run tests with code coverage report
test-coverage:
    pnpm run test:coverage

# Run tests with code coverage report, and watch for file changes to rerun
test-coverage-watch:
    pnpm run test:coverage:watch

# Run the development server
dev:
    pnpm run dev

# Build for production
build:
    pnpm run build

# Lint
lint:
    pnpm run lint

# builds Docker image for this frontend, with optional `target` build stage
build-docker target="":
    docker build \
        -f Dockerfile \
        {{ if target != "" { "--target " + target } else {""} }} \
        -t {{DOCKER_TAG}} \
        .

# Run Docker image for this frontend (built with `build-docker`)
run-docker:
    docker run {{TTY}} \
        --rm \
        {{PORT}} \
        {{DOCKER_TAG}}
