
# Show these help docs
[default]
@help:
    echo "{{GREEN}}[MLAD] database{{NORMAL}}"
    echo "{{GREEN}}>> $(pwd){{NORMAL}}"
    echo ""
    just --list --unsorted --justfile {{ source_file() }}

# Install diesel_cli
bootstrap:
    cargo install diesel_cli --no-default-features --features postgres

# Run all pending migrations
migrate:
    diesel migration run

# Revert the last applied migration
revert:
    diesel migration revert

# Revert then re-run the last migration
redo:
    migration redo

# Generate a new empty migration
new name:
    diesel migration generate {{ name }}
