[workspace]
members = ["mlad-manage-adr-lib", "mlad-manage-db-lib"]

[package]
name = "mlad-manage"
version = "0.1.0"
edition = "2024"

[dependencies]
mlad-manage-adr-lib = { path = "mlad-manage-adr-lib" }
mlad-manage-db-lib = { path = "mlad-manage-db-lib" }
clap = { version = "4", features = ["derive", "env"] }
diesel = { version = "2", features = ["postgres", "uuid"] }
argon2 = "0.5.3"
rand = "0.8.5"
uuid = { version = "1", features = ["v4", "v7"] }
chrono = { version = "0.4", features = ["clock"] }
dotenvy = "0.15"
rpassword = "7"
anyhow = "1"

[dev-dependencies]
tempfile = "3"
